### PR TITLE
Upgraded to Zookeeper 3.4.11

### PR DESCRIPTION
**Pull request by amilbourne**
Nothing very big, but it should bring in a few bug fixes.
Hopefully this is OK to merge?

### CODE REVIEW

**Comment by jplock** [comment]
Thanks

**Comment by amilbourne** [comment]
Wow - speedy response! Thanks.

**Comment by amilbourne** [comment]
Sorry to bother you, but this has built and been tagged as 'latest' on DockerHub.  That is great but it would be really good if we could use a version tag i.e. '3.4.11'.  If it isn't too much hassle, could you add a tag please?

**Comment by jplock** [comment]
Yea sorry, I'll see about doing that later today.

**Comment by jplock** [comment]
@amilbourne just pushed `3.4.11`

**Comment by amilbourne** [comment]
Thanks very much for your help.

**Pull request merged**
